import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import AppBar from "@/components/shared/AppBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="purple-dark">
      <body className="h-screen">
        <Providers>
          <AppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
